GENERIC_IMAGE_PROMPT = """Create a detailed image prompt for FluxDev based on the provided description. 
Be creative and visually compelling while staying true to the content description. 
Include specific details like camera angles, lighting conditions, visual style, and composition. 
Generate a still image with no motion. Make the prompt detailed and descriptive."""

# 不同的奇幻冒險場景描述，根據主題選擇
fantasy_adventure_scenarios = [
    "Ancient dragon's lair with treasure hoard and magical artifacts",
    "Enchanted forest with glowing mushrooms and mystical creatures",
    "Medieval castle on floating island with waterfalls cascading down",
    "Wizard's tower with swirling magical energy and floating books",
    "Dwarven forge deep in mountain with molten metal and ancient runes",
    "Elven city built in giant trees with bridges connecting platforms",
    "Crystal cave with magical formations and ethereal light sources",
    "Desert oasis with ancient ruins and mysterious portal",
    "Flying ship navigating through storm clouds and lightning",
    "Underground kingdom with glowing crystals and subterranean rivers"
]

magical_quest_scenarios = [
    "Hero's journey through mystical portal with glowing runes",
    "Magical sword in stone with ancient prophecies and destiny",
    "Wizard's spell casting with elemental magic and energy",
    "Fantasy battle scene with dragons and knights in epic combat",
    "Enchanted library with floating books and magical knowledge",
    "Mythical creature encounter in misty mountain pass",
    "Magical potion brewing with colorful ingredients and steam",
    "Ancient temple with hidden treasures and guardian spirits",
    "Flying mount soaring over fantasy landscape with castles",
    "Magical transformation scene with light and energy effects"
]

epic_battle_scenarios = [
    "Epic battle between armies of light and darkness on vast battlefield",
    "Hero facing ancient evil in dramatic confrontation with magical weapons",
    "Siege of fantasy castle with catapults and magical defenses",
    "Naval battle between pirate ships and royal fleet with sea monsters",
    "Aerial combat between flying creatures and airships",
    "Underground war between dwarves and goblins in caverns",
    "Magical duel between powerful wizards with elemental forces",
    "Cavalry charge across fantasy plains with banners flying",
    "Defense of magical barrier against dark forces",
    "Final showdown in ancient arena with cheering crowds"
]

day_trading_scenarios = [
    "Multiple monitor setup showing real-time stock charts and trading platforms",
    "Day trader analyzing candlestick patterns on high-resolution displays",
    "Trading desk with hot keys keyboard and professional trading software",
    "Intraday price movements and volume indicators on trading screens",
    "High-frequency trading setup with millisecond execution displays",
    "Day trading workspace with profit/loss tracking and risk management tools",
    "Real-time market data feeds and news terminals for active trading",
    "Scalping setup with tick charts and order book depth analysis",
    "Professional day trading office with multiple asset class monitors",
    "Technical analysis workspace with drawing tools and trend indicators",
    "Options trading platform showing Greeks and volatility surfaces",
    "Cryptocurrency day trading setup with multiple exchange interfaces",
    "Forex day trading station with currency pair charts and economic calendar",
    "Momentum trading setup tracking breakouts and volume surges",
    "Day trading risk management dashboard with position sizing tools",
    "Pre-market analysis workspace with gap scanners and news feeds",
    "Swing trading transition setup for overnight position management",
    "Pattern day trader workspace meeting PDT rule requirements",
    "Day trading journal software tracking performance metrics",
    "Live trading room setup with chat feeds and mentor guidance"
]

bear_market_scenarios = [
    "Red declining stock charts showing steep market losses and downward trends",
    "Trading floor in crisis with panicked expressions and falling market indicators",
    "Bear market symbols with downward trending arrows and negative graphs",
    "Financial stress situation with portfolio losses displayed on screens",
    "Market crash indicators showing massive sell-offs and declining values",
    "Bearish cryptocurrency displays with steep price drops and red candles",
    "Investment portfolio showing significant losses and negative returns",
    "Economic recession indicators on financial news displays and terminals",
    "Risk management crisis meeting with defensive investment strategies",
    "Market volatility displays showing high VIX and fear index readings",
    "Bear market rally signs with temporary upswings in declining trends",
    "Financial media coverage of market corrections and economic uncertainty",
    "Investment advisory meeting discussing defensive positioning strategies",
    "Bear market protection strategies with hedging tools and put options",
    "Economic indicators showing recession signals and declining GDP data",
    "Financial planning during market downturns with conservative approaches",
    "Bear market psychology analysis with fear and greed index displays",
    "Defensive investment sectors performing during economic downturns",
    "Market timing discussions during bear market phases and corrections",
    "Long-term investment perspective during temporary market declines"
]

crypto_scenarios = [
    "Bitcoin trading setup with multiple cryptocurrency exchange interfaces",
    "Blockchain technology visualization with distributed ledger networks",
    "Cryptocurrency mining farm with high-performance GPU arrays",
    "DeFi protocol interface showing liquidity pools and yield farming",
    "NFT marketplace display with digital art collections and trading",
    "Crypto wallet security setup with hardware wallets and private keys",
    "Altcoin analysis workspace with technical indicators and market data",
    "Cryptocurrency news terminal showing market sentiment and price alerts",
    "Smart contract development environment with Solidity code editors",
    "Crypto portfolio tracking dashboard with diversified digital assets",
    "Bitcoin ATM machine in modern urban financial district setting",
    "Cryptocurrency conference presentation on blockchain innovation",
    "Digital asset custody solutions with institutional-grade security",
    "Crypto derivatives trading platform with futures and options",
    "Stablecoin ecosystem display showing USDC, USDT, and DAI pairs",
    "Web3 development workspace with decentralized application interfaces",
    "Cryptocurrency regulatory compliance office with legal frameworks",
    "Bitcoin halving event analysis with supply reduction charts",
    "Layer 2 scaling solutions display with Lightning Network interfaces",
    "Crypto tax preparation workspace with transaction tracking software"
]

real_estate_scenarios = [
    "Modern luxury home interior with open floor plan and premium finishes",
    "Real estate agent presenting property portfolio on digital tablet",
    "Commercial office building lobby with marble floors and glass elevators",
    "Residential neighborhood aerial view showing property development",
    "Real estate investment analysis workspace with property valuation reports",
    "Property management office with tenant screening and lease agreements",
    "Home staging setup with furniture and decorative elements",
    "Real estate market analysis dashboard with price trends and forecasts",
    "Mortgage application meeting with loan documents and calculators",
    "Property inspection checklist with professional assessment tools",
    "Real estate photography setup capturing interior and exterior shots",
    "Investment property renovation planning with contractor estimates",
    "Real estate auction environment with bidding paddles and displays",
    "Property appraisal workspace with comparable sales analysis",
    "Real estate CRM system managing client relationships and listings",
    "Commercial real estate lease negotiation in modern conference room",
    "Residential property showing with virtual tour technology setup",
    "Real estate investment trust portfolio analysis on financial screens",
    "Property tax assessment documents with municipal evaluation reports",
    "Real estate development site with architectural plans and permits",
    "Home buyer consultation with first-time purchase guidance materials",
    "Property maintenance scheduling system with repair work orders",
    "Real estate market research with demographic and economic data",
    "Rental property income tracking with cash flow projections",
    "Real estate closing ceremony with keys and signed contracts",
    "Property insurance evaluation with coverage assessment documents",
    "Real estate marketing materials with professional photography portfolio",
    "Investment property analysis with cap rates and ROI calculations",
    "Real estate legal documents review with title searches and deeds",
    "Property management software dashboard with maintenance requests",
    "Real estate networking event with industry professionals gathering",
    "Home equity analysis with property value appreciation charts",
    "Real estate crowdfunding platform showing investment opportunities",
    "Property flipping project planning with budget and timeline sheets",
    "Real estate mentorship meeting with experienced investor guidance",
    "Commercial property due diligence with financial and legal reviews",
    "Real estate podcast recording setup discussing market trends",
    "Property wholesaling workspace with contract assignments and deals",
    "Real estate education seminar with investment strategy presentations",
    "Vacation rental property management with booking and guest services",
    "Real estate technology demonstration with AR property visualization",
    "Property asset management meeting with portfolio optimization strategies",
    "Real estate market timing analysis with buying and selling indicators",
    "International real estate investment with global property portfolios",
    "Real estate partnership formation with joint venture agreements",
    "Property syndication presentation with investor group meetings",
    "Real estate tax strategy planning with depreciation and 1031 exchanges",
    "Luxury real estate showcase with high-end property presentations",
    "Real estate data analytics workspace with predictive modeling tools",
    "Property acquisition financing with bank loan application processes"
]

global_market_scenarios = [
    "London Stock Exchange trading floor with international market displays",
    "Tokyo financial district skyline during morning market opening hours",
    "Frankfurt banking headquarters with European Central Bank connections",
    "Hong Kong trading terminals showing Asian market indicators",
    "New York Federal Reserve building with global monetary policy displays",
    "Singapore financial hub with multi-currency trading platforms",
    "Swiss private banking office with international wealth management",
    "Dubai International Financial Centre with Middle Eastern market data",
    "Shanghai Stock Exchange with Chinese market capitalizations",
    "Toronto Stock Exchange displaying Canadian commodity markets",
    "Sydney financial district with Australian mining stock indicators",
    "Mumbai stock exchange floor with Indian market growth charts",
    "São Paulo financial center with Brazilian emerging market data",
    "Moscow exchange terminals showing Russian energy sector stocks",
    "Mexico City financial district with Latin American market indicators",
    "Seoul trading floor with Korean technology stock displays",
    "Tel Aviv stock exchange with Israeli innovation sector data",
    "Johannesburg financial center with African mining stock indicators",
    "Global foreign exchange trading desk with major currency pairs",
    "International commodities trading floor with gold and oil prices",
    "Cross-border investment analysis with emerging market portfolios",
    "Global economic summit with international financial ministers",
    "Multinational corporation boardroom with worldwide market analysis",
    "International banking conference with global regulatory discussions",
    "World Bank headquarters with development finance project displays",
    "International Monetary Fund meeting room with global crisis management",
    "G20 finance summit with international economic cooperation",
    "Global investment fund office with diversified country allocations",
    "International trade finance desk with export-import documentation",
    "Offshore banking center with international tax optimization",
    "Global macro hedge fund with worldwide economic trend analysis",
    "International pension fund meeting with global asset allocation",
    "Sovereign wealth fund office with strategic international investments",
    "Global private equity firm with cross-border acquisition analysis",
    "International venture capital meeting with worldwide startup funding",
    "Cross-border mergers and acquisitions advisory workspace",
    "Global supply chain finance with international trade settlements",
    "International insurance company with worldwide risk assessment",
    "Global real estate investment with international property markets",
    "Multinational tax advisory with international compliance frameworks",
    "Global financial technology hub with international fintech solutions",
    "International development bank with emerging market infrastructure",
    "Global carbon credit trading with international climate finance",
    "International arbitrage trading desk with cross-market opportunities",
    "Global wealth management with international client portfolios",
    "International Islamic finance center with Sharia-compliant investments",
    "Global impact investing with international sustainable development",
    "International crisis management center with global market stability",
    "Global financial intelligence unit with international compliance monitoring",
    "International central bank cooperation with global monetary coordination"
]

strategies_scenarios = [
    "Chess pieces arranged on marble surface representing strategic financial planning",
    "Golden scales balancing different investment symbols in dramatic lighting",
    "Maze pathway made of paper money leading to financial freedom",
    "Abstract geometric shapes representing portfolio diversification strategies",
    "Compass pointing towards multiple financial goal destinations",
    "Bridge made of coins spanning across a river of opportunity",
    "Tree with branches growing different currency leaves in autumn colors",
    "Hourglass filled with gold coins measuring time value of money",
    "Ladder made of financial documents ascending towards success",
    "Shield protecting valuable assets from market storms",
    "Puzzle pieces forming complete financial strategy picture",
    "Mountain peak representing long-term investment summit achievement",
    "Garden with different investment plants growing at various stages",
    "Lighthouse guiding ships through volatile market waters",
    "Key unlocking treasure chest filled with diversified investments",
    "Balance beam with risk and reward weights in equilibrium",
    "Roadmap with multiple financial milestone markers along the path",
    "Fortress walls protecting wealth from external financial threats",
    "Seed sprouting into money tree representing compound growth",
    "Clock mechanism with gears representing systematic investment timing",
    "Arrow splitting into multiple successful investment directions",
    "Foundation stones building towards financial security structure",
    "Telescope focused on distant financial goal constellation",
    "Blueprint drawings for constructing wealth building strategies",
    "Domino effect showing positive financial momentum chain reaction",
    "Fishing net catching various investment opportunities from market ocean",
    "Pyramid structure with different asset classes forming stable base",
    "Umbrella protecting against financial rain and market downpours",
    "Magnifying glass examining fine details of investment strategies",
    "Stepping stones crossing stream towards financial independence",
    "Lock and key representing secured investment protection strategies",
    "Windmill harnessing market forces for consistent returns",
    "Anchor keeping portfolio stable during turbulent market conditions",
    "Map with treasure X marking optimal investment allocation spots",
    "Prism splitting white light into spectrum of investment options",
    "Seesaw demonstrating risk-return balance in strategic planning",
    "Funnel channeling market opportunities into focused investment strategy",
    "Gear system showing interconnected financial planning mechanisms",
    "Thermometer measuring market temperature for strategic timing",
    "Crystal ball revealing future financial possibilities and outcomes",
    "Phoenix rising from ashes representing financial recovery strategies",
    "Iceberg showing hidden depths of comprehensive financial planning",
    "Spider web catching profitable opportunities in strategic pattern",
    "Pendulum swinging between conservative and aggressive investment approaches",
    "Kaleidoscope creating patterns from diverse investment fragments",
    "Lever system demonstrating financial leverage and strategic positioning",
    "Constellation map connecting financial goals with strategic pathways",
    "Origami crane folded from dollar bills representing transformation",
    "Sundial casting shadows on investment timing decisions",
    "Butterfly emerging from cocoon symbolizing financial metamorphosis"
]

risk_vs_reward_scenarios = [
    "Tightrope walker balancing on golden rope over deep canyon with treasure chest",
    "Double-sided coin spinning in mid-air showing opportunity and danger",
    "Mountain climber ascending steep cliff with golden summit in misty clouds",
    "Dice rolling on marble table with diamonds and coal as possible outcomes",
    "Scales weighing feathers against gold bars in dramatic chiaroscuro lighting",
    "Butterfly wings showing fragile beauty next to sharp thorns with roses",
    "Bridge crossing turbulent river with safe shore and treasure island visible",
    "Volcano crater containing both molten danger and precious gemstone deposits",
    "Storm clouds parting to reveal rainbow leading to pot of gold",
    "Spider web glistening with dewdrops, both trap and artistic masterpiece",
    "Ice formations creating both slippery danger and crystalline beauty",
    "Fire consuming old growth while new green shoots emerge from ashes",
    "Ocean waves showing both destructive power and life-giving potential",
    "Glass orb containing swirling storm with golden light at center",
    "Thorny rose bush with magnificent blooms protected by sharp defenses",
    "Cliff edge overlooking vast valley with eagles soaring below",
    "Mirror maze reflecting both escape routes and dead-end traps",
    "Pendulum swinging between two containers of sand and gold",
    "Lightning striking tree creating both destruction and new growth patterns",
    "Hourglass with sand falling through narrow opening, time as risk factor",
    "Yin-yang symbol made from contrasting materials like coal and diamond",
    "Seesaw with heavy anchor on one side, helium balloons on other",
    "Chess board with pieces positioned in high-stakes endgame scenario",
    "Trapeze artists mid-flight with safety net visible far below",
    "Waterfall cascading over precious stones into unknown depths",
    "Hot air balloon floating between storm clouds and sunny skies",
    "Maze built from playing cards with exit paths marked in gold",
    "Compass needle pointing between magnetic north and treasure location",
    "Butterfly collector's net poised over rare specimen in dangerous terrain",
    "Seed pods opening to release both poisonous and beneficial elements",
    "Crystal cave with beautiful formations and unstable ceiling structure",
    "Lighthouse beam cutting through fog toward both safe harbor and rocky shores",
    "Balanced rocks creating natural sculpture that could topple any moment",
    "Golden apple hanging from branch over precipice, requiring dangerous reach",
    "Prism refracting light into both blinding intensity and beautiful spectrum",
    "Wind chimes creating harmony while weathering destructive storm forces",
    "Iceberg showing small visible portion above vast hidden mass below",
    "Labyrinth with multiple paths leading to rewards and dead ends",
    "Telescope focused on distant star that could be salvation or supernova",
    "Garden gate opening to paradise garden with warning signs posted",
    "Tidal pool ecosystem balancing delicate life with crushing wave power",
    "Aerial silk performer suspended between safety platform and void",
    "Phoenix feather glowing with regenerative power amid smoldering ruins",
    "Crystal ball showing multiple possible futures in swirling mists",
    "Rope bridge spanning chasm with beautiful valley visible far below",
    "Magnifying glass focusing sunlight into both harmful ray and beneficial warmth",
    "Kaleidoscope creating beauty from fragments of broken valuable materials",
    "Weather vane pointing between approaching storm and clearing skies",
    "Quicksand pit surrounded by oasis with palm trees and fresh water",
    "Diamond mine shaft descending into darkness with promise of riches"
]

astrology_scenarios = [
    "Aries constellation with ram symbolism and fire elements",
    "Taurus constellation with bull imagery and earth elements", 
    "Gemini constellation with twin symbolism and air elements",
    "Cancer constellation with crab imagery and water elements",
    "Leo constellation with lion symbolism and fire elements",
    "Virgo constellation with maiden imagery and earth elements",
    "Libra constellation with scales symbolism and air elements", 
    "Scorpio constellation with scorpion imagery and water elements",
    "Sagittarius constellation with archer symbolism and fire elements",
    "Capricorn constellation with goat imagery and earth elements",
    "Aquarius constellation with water bearer symbolism and air elements",
    "Pisces constellation with fish imagery and water elements",
    "Solar eclipse with mystical astrological significance",
    "Lunar eclipse with celestial astrological meaning",
    "Mercury retrograde with cosmic communication effects",
    "Venus transit with love and beauty astrological influence",
    "Mars opposition with warrior energy and conflict",
    "Jupiter conjunction with expansion and abundance",
    "Saturn return with life lessons and transformation",
    "Uranus square with sudden change and revolution",
    "Neptune trine with dreams and spiritual awakening",
    "Pluto transformation with death and rebirth cycles",
    "Full moon in different zodiac signs with ritual significance",
    "New moon manifestation with astrological timing",
    "Planetary alignment with cosmic significance",
    "Astrological birth chart with natal planet positions",
    "Tarot cards combined with astrological symbolism",
    "Crystal formations aligned with zodiac energies",
    "Sacred geometry patterns reflecting celestial movements",
    "Astrological houses with life theme representations",
    "Elemental balance of fire, earth, air, water signs",
    "Cardinal, fixed, mutable sign energy expressions",
    "Astrological aspects and angular relationships",
    "Celestial bodies in retrograde motion effects",
    "Zodiac wheel with seasonal and temporal divisions",
    "Astrological transits and their life influences",
    "Lunar phases and their emotional significance",
    "Solar return charts and annual cycles",
    "Composite charts and relationship astrology",
    "Progressed charts and life evolution timing",
    "Astrological remedies and healing practices",
    "Vedic astrology with Eastern philosophical elements",
    "Chinese astrology with animal year symbolism",
    "Mayan astrology with calendar and cosmic cycles",
    "Celtic astrology with tree and nature symbolism",
    "Egyptian astrology with deity and pyramid imagery",
    "Babylonian astrology with ancient wisdom traditions",
    "Modern psychological astrology with therapeutic themes",
    "Evolutionary astrology with soul purpose exploration",
    "Electional astrology with optimal timing selection"
]
    
